//
// Generated file, do not edit! Created by opp_msgtool 6.3 from TDMA_Messages.msg.
//

#ifndef __TDMA_MESSAGES_M_H
#define __TDMA_MESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TDMADataPacket;
class TDMAGrantRequest;
class TDMAGrantReply;
/**
 * Class generated from <tt>TDMA_Messages.msg:6</tt> by opp_msgtool.
 * <pre>
 * packet TDMADataPacket
 * {
 *     int srcId;
 *     int destId;
 *     string payload;
 *     // 携带本次释放的时隙索引 (如果为-1则不释放)
 *     int releasedSlotIndex = -1;
 * }
 * </pre>
 */
class TDMADataPacket : public ::omnetpp::cPacket
{
  protected:
    int srcId = 0;
    int destId = 0;
    omnetpp::opp_string payload;
    int releasedSlotIndex = -1;

  private:
    void copy(const TDMADataPacket& other);

  protected:
    bool operator==(const TDMADataPacket&) = delete;

  public:
    TDMADataPacket(const char *name=nullptr, short kind=0);
    TDMADataPacket(const TDMADataPacket& other);
    virtual ~TDMADataPacket();
    TDMADataPacket& operator=(const TDMADataPacket& other);
    virtual TDMADataPacket *dup() const override {return new TDMADataPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual int getDestId() const;
    virtual void setDestId(int destId);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);

    virtual int getReleasedSlotIndex() const;
    virtual void setReleasedSlotIndex(int releasedSlotIndex);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TDMADataPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TDMADataPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TDMA_Messages.msg:15</tt> by opp_msgtool.
 * <pre>
 * // 申请分组 (RTS)
 * packet TDMAGrantRequest
 * {
 *     int srcId;
 * 
 *     // 目标节点ID列表 (对应每个业务时隙，如果某时隙不申请则填-1)
 *     int targetNodeIds[];
 * 
 *     // 业务时隙申请优先级/概率 (对应每个业务时隙)
 *     double priorities[];
 * 
 *     // 业务时隙占用情况 (Occupier ID)
 *     int occupancyInfo[];
 *     // 业务时隙占用信息的跳数距离 (0=发送者自己占用, 1=发送者的一跳邻居占用...)
 *     int occupancyHops[];
 * }
 * </pre>
 */
class TDMAGrantRequest : public ::omnetpp::cPacket
{
  protected:
    int srcId = 0;
    int *targetNodeIds = nullptr;
    size_t targetNodeIds_arraysize = 0;
    double *priorities = nullptr;
    size_t priorities_arraysize = 0;
    int *occupancyInfo = nullptr;
    size_t occupancyInfo_arraysize = 0;
    int *occupancyHops = nullptr;
    size_t occupancyHops_arraysize = 0;

  private:
    void copy(const TDMAGrantRequest& other);

  protected:
    bool operator==(const TDMAGrantRequest&) = delete;

  public:
    TDMAGrantRequest(const char *name=nullptr, short kind=0);
    TDMAGrantRequest(const TDMAGrantRequest& other);
    virtual ~TDMAGrantRequest();
    TDMAGrantRequest& operator=(const TDMAGrantRequest& other);
    virtual TDMAGrantRequest *dup() const override {return new TDMAGrantRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual void setTargetNodeIdsArraySize(size_t size);
    virtual size_t getTargetNodeIdsArraySize() const;
    virtual int getTargetNodeIds(size_t k) const;
    virtual void setTargetNodeIds(size_t k, int targetNodeIds);
    virtual void insertTargetNodeIds(size_t k, int targetNodeIds);
    [[deprecated]] void insertTargetNodeIds(int targetNodeIds) {appendTargetNodeIds(targetNodeIds);}
    virtual void appendTargetNodeIds(int targetNodeIds);
    virtual void eraseTargetNodeIds(size_t k);

    virtual void setPrioritiesArraySize(size_t size);
    virtual size_t getPrioritiesArraySize() const;
    virtual double getPriorities(size_t k) const;
    virtual void setPriorities(size_t k, double priorities);
    virtual void insertPriorities(size_t k, double priorities);
    [[deprecated]] void insertPriorities(double priorities) {appendPriorities(priorities);}
    virtual void appendPriorities(double priorities);
    virtual void erasePriorities(size_t k);

    virtual void setOccupancyInfoArraySize(size_t size);
    virtual size_t getOccupancyInfoArraySize() const;
    virtual int getOccupancyInfo(size_t k) const;
    virtual void setOccupancyInfo(size_t k, int occupancyInfo);
    virtual void insertOccupancyInfo(size_t k, int occupancyInfo);
    [[deprecated]] void insertOccupancyInfo(int occupancyInfo) {appendOccupancyInfo(occupancyInfo);}
    virtual void appendOccupancyInfo(int occupancyInfo);
    virtual void eraseOccupancyInfo(size_t k);

    virtual void setOccupancyHopsArraySize(size_t size);
    virtual size_t getOccupancyHopsArraySize() const;
    virtual int getOccupancyHops(size_t k) const;
    virtual void setOccupancyHops(size_t k, int occupancyHops);
    virtual void insertOccupancyHops(size_t k, int occupancyHops);
    [[deprecated]] void insertOccupancyHops(int occupancyHops) {appendOccupancyHops(occupancyHops);}
    virtual void appendOccupancyHops(int occupancyHops);
    virtual void eraseOccupancyHops(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TDMAGrantRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TDMAGrantRequest& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TDMA_Messages.msg:31</tt> by opp_msgtool.
 * <pre>
 * // 回复分组 (CTS)
 * packet TDMAGrantReply
 * {
 *     int srcId;
 * 
 *     // 业务时隙回复信息 (对应每个业务时隙: 同意则填申请者ID，NACK则填-2，无冲突/闲置填-1)
 *     int slotGrantDecisions[];
 * 
 *     // 更新后的业务时隙占用情况
 *     int occupancyInfo[];
 *     // 业务时隙占用信息的跳数距离
 *     int occupancyHops[];
 * }
 * </pre>
 */
class TDMAGrantReply : public ::omnetpp::cPacket
{
  protected:
    int srcId = 0;
    int *slotGrantDecisions = nullptr;
    size_t slotGrantDecisions_arraysize = 0;
    int *occupancyInfo = nullptr;
    size_t occupancyInfo_arraysize = 0;
    int *occupancyHops = nullptr;
    size_t occupancyHops_arraysize = 0;

  private:
    void copy(const TDMAGrantReply& other);

  protected:
    bool operator==(const TDMAGrantReply&) = delete;

  public:
    TDMAGrantReply(const char *name=nullptr, short kind=0);
    TDMAGrantReply(const TDMAGrantReply& other);
    virtual ~TDMAGrantReply();
    TDMAGrantReply& operator=(const TDMAGrantReply& other);
    virtual TDMAGrantReply *dup() const override {return new TDMAGrantReply(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual void setSlotGrantDecisionsArraySize(size_t size);
    virtual size_t getSlotGrantDecisionsArraySize() const;
    virtual int getSlotGrantDecisions(size_t k) const;
    virtual void setSlotGrantDecisions(size_t k, int slotGrantDecisions);
    virtual void insertSlotGrantDecisions(size_t k, int slotGrantDecisions);
    [[deprecated]] void insertSlotGrantDecisions(int slotGrantDecisions) {appendSlotGrantDecisions(slotGrantDecisions);}
    virtual void appendSlotGrantDecisions(int slotGrantDecisions);
    virtual void eraseSlotGrantDecisions(size_t k);

    virtual void setOccupancyInfoArraySize(size_t size);
    virtual size_t getOccupancyInfoArraySize() const;
    virtual int getOccupancyInfo(size_t k) const;
    virtual void setOccupancyInfo(size_t k, int occupancyInfo);
    virtual void insertOccupancyInfo(size_t k, int occupancyInfo);
    [[deprecated]] void insertOccupancyInfo(int occupancyInfo) {appendOccupancyInfo(occupancyInfo);}
    virtual void appendOccupancyInfo(int occupancyInfo);
    virtual void eraseOccupancyInfo(size_t k);

    virtual void setOccupancyHopsArraySize(size_t size);
    virtual size_t getOccupancyHopsArraySize() const;
    virtual int getOccupancyHops(size_t k) const;
    virtual void setOccupancyHops(size_t k, int occupancyHops);
    virtual void insertOccupancyHops(size_t k, int occupancyHops);
    [[deprecated]] void insertOccupancyHops(int occupancyHops) {appendOccupancyHops(occupancyHops);}
    virtual void appendOccupancyHops(int occupancyHops);
    virtual void eraseOccupancyHops(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TDMAGrantReply& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TDMAGrantReply& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TDMADataPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<TDMADataPacket*>(ptr.get<cObject>()); }
template<> inline TDMAGrantRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<TDMAGrantRequest*>(ptr.get<cObject>()); }
template<> inline TDMAGrantReply *fromAnyPtr(any_ptr ptr) { return check_and_cast<TDMAGrantReply*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TDMA_MESSAGES_M_H

